### ISSUE TITLE
为什么我不能准确生成ner.txt文件

### ISSUE THREAD

**Issue by angeluau** [Fengfeng1024/SOHU-baseline#1]
楼主可以分享至我的邮箱taeyanglucky@qq.com吗

**Comment by Chevalier1024** [comment]
出什么错了么，麻烦把错误截图贴上来

**Comment by angeluau** [comment]
没报错但是无法生成，我设置了10个 epoches，但是最后没有生成ner.txt


 
---原始邮件---
发件人: "Fengfeng1024"<notifications@github.com>
发送时间: 2019年4月30日(星期二) 上午10:32
收件人: "Fengfeng1024/SOHU-baseline"<SOHU-baseline@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"angeluau"<2215346277@qq.com>;
主题: Re: [Fengfeng1024/SOHU-baseline] 为什么我不能准确生成ner.txt文件 (#1)



出什么错了么，麻烦把错误截图贴上来

**Comment by Chevalier1024** [comment]
你可以自己调试一下。看那个on_epoch_end函数，10个epoch的话还没到早停，自然就不会预测了

**Comment by angeluau** [comment]
我是将early stopping设置为了5

---原始邮件---
发件人: "Fengfeng1024"<notifications@github.com>
发送时间: 2019年4月30日(星期二) 上午10:46
收件人: "Fengfeng1024/SOHU-baseline"<SOHU-baseline@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"angeluau"<2215346277@qq.com>;
主题: Re: [Fengfeng1024/SOHU-baseline] 为什么我不能准确生成ner.txt文件 (#1)



你可以自己调试一下。看那个on_epoch_end函数，10个epoch的话还没到早停，自然就不会预测了
 
&mdash;
